### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by JaredSartin** [gogoprog/gengine#1]
Hey!

Loved the direction the first version of the engine was going. Any ETA for the next version or at least a functional features list?

Cheers

**Comment by gogoprog** [comment]
Hello,

Thanks and yes I'm a late on releasing... Sorry for that :)

The current state has enough functionalities to be released but it has been built/tested on linux only at this moment.

Any help on building the engine/librairies on OsX or Windows is welcome!

**Comment by gogoprog** [comment]
A bit of update :

I'm working on a new system to generate distributed versions.
It will use the emscripten version of the engine, so will be platform-agnostic.

Coming very soon (a week) so I close this issue.
